### ISSUE TITLE
Incorrect kick message on join when not whitelisted

### ISSUE THREAD

**Issue by Orcinuss** [Quetzi/Whitelister#2]
Using v3.1.8 for 1.10.2

When a user is not on the whitelist, players get disconnected with the message:

"Internal Exception: java.io.IOException: Connection reset by peer"

instead of the message they are supposed to receive when not whitelisted. This can be misleading because players think it is an error on their end instead of the server's end.

Here is my whitelister.cfg file: http://pastebin.com/xeDwRWVj

Here is the error outputted from the console: http://pastebin.com/Ra6KYy0M

Thanks, Orc

**Comment by Quetzi** [comment]
There is not a lot I can do to solve this, the incorrect disconnect message is being shown on the client which Whitelister does not touch. The relevant code I use to do this is here: https://github.com/Quetzi/Whitelister/blob/master/src/main/java/net/quetzi/whitelister/handlers/WhitelistEventHandler.java#L34 which is the forge/vanilla provided method to kick a player from the server with a reason. In short, there is a bug, but it isn't on my side, sorry.
